### ISSUE TITLE
Stream Title is almost off Screen on iOS and Mac

### ISSUE THREAD

**Issue by wakehood** [arkavo-org/app#24]
Found in Version Beta 1.0.0-beta.0

When a stream is selected, the Title on the screen view is almost off screen. 

![IMG_2348](https://github.com/user-attachments/assets/514f93cf-8676-4cba-8ed7-3c7a407ffec8)

![Title Almost off Page](https://github.com/user-attachments/assets/2eef6f2a-2e3d-48da-9149-097d278e978b)

![Screenshot 2024-08-31 at 11 25 11 AM](https://github.com/user-attachments/assets/13be3967-fcb4-43ec-b4f9-93f395000baf)

**Comment by arkavo-com** [comment]
Saw during the beta test too
