### ISSUE TITLE
Create Profile and View Profile

### ISSUE THREAD

**Issue by wakehood** [arkavo-org/app#25]
Version 1.0.0-beta.0

On iOS you can swipe down to get rid of the sheet.

On Mac you have to press Esc to get rid of the sheet.

most obvious would be to have "X" to quit

**Comment by arkavo-com** [comment]
<img width="229" alt="Screenshot 2024-09-02 at 12 34 48 PM" src="https://github.com/user-attachments/assets/b202ed4b-16b1-449e-a977-147303ae39b7">

Go ahead and update to wireframe
