### ISSUE TITLE
If you add you own Stream, you no longer can get to the default streams

### ISSUE THREAD

**Issue by wakehood** [arkavo-org/app#26]
1.0.0-beta.0

Upon first start up. Select Engage and you see the default streams. (UI, Swift, Design etc)

Create a stream in My Streams. Then select Engage and only the new stream is displayed.

Should be able to see default streams and the new stream as well.

![IMG_2351](https://github.com/user-attachments/assets/d8ce09fc-cc7f-46b6-92c6-52136811334c)
![IMG_2350](https://github.com/user-attachments/assets/1d2134ed-1d88-4909-b2cf-8690b1b967be)

**Comment by arkavo-com** [comment]
Default streams should be removed.  
User should see their streams.  And then see streams from others (new StreamService perhaps)

**Comment by arkavo-com** [comment]
Default streams should be removed.
