### ISSUE TITLE
Streams Don't persist.

### ISSUE THREAD

**Issue by wakehood** [arkavo-org/app#27]
1.0.0-beta.0

Create a stream.

Close App

Stream is no longer there.  

Should be persisted

**Comment by arkavo-com** [comment]
Perhaps add `@Model` here https://github.com/arkavo-org/app/blob/main/Arkavo/Arkavo/Stream.swift#L5

**Comment by arkavo-com** [comment]
commit with fix https://github.com/arkavo-org/app/pull/28/commits/1a77260941540259be95b4d7eb751eaec9ffd343
